### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by DrBumlehund** [DrBumlehund/rflr#3]
## Description 
Make an SQLite database to store win statistics.

## Links?
[Android | SQLite](https://developer.android.com/training/basics/data-storage/databases.html)

## TODO:
- [ ] Define SQL schema
- [ ] Create SQLite file if non exists
- [ ] Write stuff to SQLite file
- [ ] Other?
