### ISSUE TITLE
Accelerometer

### ISSUE THREAD

**Issue by DrBumlehund** [DrBumlehund/rflr#4]
## Description
Define logic for using the Accelerometer to raffle the dice with.

## Links?
[Android | Sensors](https://developer.android.com/guide/topics/sensors/sensors_overview.html)
[Android | Motion Sensors](https://developer.android.com/guide/topics/sensors/sensors_motion.html)

## TODO:
- [ ] Create events for raffling
- [ ] Finetune the stuff maybe? ¯\_(ツ)_/¯
- [ ] Create Code for Raffling

**Comment by msjaelland** [comment]
http://stackoverflow.com/questions/5271448/how-to-detect-shake-event-with-android
